### ISSUE TITLE
MC-1809 / leaf decay.

### ISSUE THREAD

**Issue by Khikki** [jss2a98aj/BugTorch#1]
Hello, hello. Roadhog360 recommended creating issue in BugTorch.

From the old versions, there is a bug that when generating the foliage of large trees begins to decaying.

https://youtu.be/Y5mqmsUgW-4
https://bugs.mojang.com/browse/MC-95657
https://bugs.mojang.com/browse/MC-1809
https://bugs.mojang.com/browse/MC-98557

From what I have heard, the radius that leaves can survive near a log has been increased to 6.
In subsequent versions, this problem was resolved, take a look if you have any free time.

**Comment by jss2a98aj** [comment]
I have a fix for it in an upcoming version. I should have a beta ready in a few days, as there are some other bugs I have been attempting to fix too.

**Comment by Khikki** [comment]
Hey, what about beta? :)

**Comment by jss2a98aj** [comment]
There may be some oddities with this build, but go ahead and give it a try. https://www.dropbox.com/s/rf4fktiya7kedpk/BugTorch-1.0.4b2.jar?dl=1

**Comment by Khikki** [comment]
Hello, version 1.0.4b2 proved to be fine, however: the problem with decaying foliage has not yet been solved.
![Uploading 2021-03-02_18.09.55.png…]()

**Comment by jss2a98aj** [comment]
Try with a fresh config or ensure that "fixShearedBlocksDropExtraItems" is true. The fix is currently piggybacking off of a mixin controlled by that config option.

**Comment by Khikki** [comment]
Yes, I made sure that "fixShearedBlocksDropExtraItems" is true.
![image](https://user-images.githubusercontent.com/35336209/109746413-04e4ed00-7bde-11eb-9eb9-5787ab28ad0b.png)
However, the foliage is still rotting, a screenshot from my modpacks, however, the exact same reaction was without mods.
![2021-03-03_05 04 04](https://user-images.githubusercontent.com/35336209/109746781-a0765d80-7bde-11eb-8189-ad80c3109dd2.png)

**Comment by jss2a98aj** [comment]
Odd. I'm not certain why that isn't working.

**Comment by Khikki** [comment]
Do you think this can be fixed? :(

**Comment by jss2a98aj** [comment]
Yeah. I should be able to get it working at some point.

**Comment by jss2a98aj** [comment]
This beta should fix the issue the last one had: https://www.dropbox.com/s/lsgsrh7lur4oul0/BugTorch-1.0.4b3.jar?dl=1

**Comment by Khikki** [comment]
Yes, you did a great job! Everything works as it should. It remains to solve the problem with WitchingGadgets, I am very happy thanks again!

**Comment by Khikki** [comment]
I would also like to ask your advice about mod trees, I don't think they are as easy to fix as vanilla trees, but I decided to ask you a question about this.

**Comment by jss2a98aj** [comment]
While those fixes should be implemented per mod, I may try to make fixes for some that are no longer being updated.

**Comment by jss2a98aj** [comment]
I will fix Natura on its end, but the other two will likely need fixed with mixins.

**Comment by jss2a98aj** [comment]
The fix for this is now officially included in version 1.1.0.
