### ISSUE TITLE
BugTorch 1.2.1 breaks loading progress bar mod (1.2.0 worked)

### ISSUE THREAD

**Issue by kotmatross28729** [jss2a98aj/BugTorch#14]
### I use a translator, so I apologize in advance if there are  ( *"oak" translations** )

There is a mod like [Loading Progress Bar](https://github.com/jbredwards/Loading-Progress-Bar/tree/1.7.10)
in bugtorch 1.2.0 release it worked, but in version 1.2.1 it no longer works

to see the Loading Progress Bar work, you need to run a VERY large modpack
(in the video, a modpack containing 120 mods)

instead of  "loading terrain" it writes ***"world transformation"**** (actually not ""world transformation"", I don't know how to translate correctly, in general, not loading terrain)

(recording lags a bit)

BugTorch 1.2.0 (work)

https://user-images.githubusercontent.com/110309314/218450024-07864491-56af-4822-a20b-74c46742467c.mp4

BugTorch 1.2.1 (does not work)

https://user-images.githubusercontent.com/110309314/218450036-ba805602-026e-4b9c-9801-868f4b435bc8.mp4

**Comment by makamys** [comment]
On the mod's CurseForge page, there's [a comment](https://www.curseforge.com/minecraft/mc-mods/loading-progress-bar?comment=2) that says the `skipInitialWorldChunkLoad` option is responsible for this.

The mod is very small though ([only a single class!](https://github.com/jbredwards/Loading-Progress-Bar/blob/509d4737880fa6adb900fbca34b504506dfb028a/src/main/java/git/jbredwards/lpb/Main.java)), so we could just merge it into BugTorch or CoreTweaks with better compatibility.

**Comment by kotmatross28729** [comment]
Oh yeah, disabling skipInitialWorldChunkLoad helps, thanks a lot!
(and yes, I would like it to be merged into one of these mods, that would be very cool)

**Comment by jss2a98aj** [comment]
BugTorch 1.2.0 was failing to apply mixins for some people. Sometimes failing to apply mixins was fixed in 1.2.1. I think the loading bar was working with 1.2.0 because the conflicting mixin was not applied.

Adding a similar feature in as makamys suggested is probably how I will fix the problem.
