### ISSUE TITLE
Unimixins +optifine + bug torch bug

### ISSUE THREAD

**Issue by reuben-matus** [jss2a98aj/BugTorch#15]
For some reason using unimixins, optifine and bug torch causes the player to be unable to change settings in optifine

**Comment by DarianLStephens** [comment]
Is that not solved by the release that just happened, 1.2.5?

**Comment by makamys** [comment]
Can't reproduce, so this is probably an issue with one of your other mods (lwjgl3ify perhaps?). Please post a full mod list.

**Comment by jss2a98aj** [comment]
It is an issue only if the conflicting setting is enabled. New installs of 1.2.5 will not have an issue, but users of 1.2.3 or 1.2.4 will need to manually disable the "fasterOptionInteractions" setting.
