### ISSUE TITLE
(Suggestion) 

### ISSUE THREAD

**Issue by bessonowjaroslaw** [jss2a98aj/BugTorch#24]
1:https://legacy.curseforge.com/minecraft/mc-mods/better-placement
2:https://legacy.curseforge.com/minecraft/mc-mods/bow-infinity-fix
3:https://legacy.curseforge.com/minecraft/mc-mods/friendly-fire
add as a feature

**Comment by jss2a98aj** [comment]
I do not plan to duplicate features from mods that appear to work fine already.
