### ISSUE TITLE
Allow other mods that provide some kind of mixin version to work with this mod. SpongeMixins is kinda useless now anyway.

### ISSUE THREAD

**Issue by MagmaBro123** [jss2a98aj/BugTorch#8]
Title. Mods like Et Futurum (iirc), MixinBooterLegacy, FalsePatternLib (iirc) etc.

You could probably make use of FPLib's other useful features as well.

**Comment by jss2a98aj** [comment]
BugTorch doesn't ship Mixins directly. I don't intend to write my own mod jar loader, and SpongeMixins has one that is widely supported. So long as something with SpongeMixins 1.3 functionality is present it will work fine. This includes GasStation, GTNHMixins, and of course SpongeMixins itself.
